
services:
  database:
    image: postgres:15
    container_name: web_postgres_db
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: web_db
    ports:
      - "5432:5432"

