version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: employmee_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin